spring:
  main:
    allow-circular-references: true
  config:
    import: local.properties
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${PG_HOST}/javadev
    username: ${PG_USER}
    password: ${PG_PASSWORD}
  flyway:
    baseline-on-migrate: true
#    enabled: false
server:
  port: ${SERVER_PORT}
keycloak:
  auth-server-url: ${KEYCLOAK_HOST}
  realm: medonline
  resource: spring-security
  public-client: false
  security-constraints[0]:
    securityCollections[0]:
      patterns[0]: /api/v1/patient/*
      patterns[1]: /api/v1/specialization/*
      patterns[2]: /api/v1/service/*
      patterns[3]: /api/v1/doctor/*
      patterns[4]: /api/v1/manager/*
    authRoles[0]: regular_user
  credentials:
    secret: ${KEYCLOAK_SECRET}
  bearer-only: true
#  credentials: spring-public


springdoc:
  swagger-ui:
    path: /swagger-ui
